name: NopalShop
version: '1.0-SNAPSHOT'
main: org.Nopal.nopalShop.NopalShop
api-version: '1.21'
authors: [ Nopal ]
description: Nopal Shop la apa lagi
depend: [Vault]
commands:
  nsreload:
    usage: /<command>
    description: reload nopal shop
  shop:
    usage: /<command>
    description: open nopal shop